server:
port: 8080
servlet:
context-path: /

spring:
datasource:
url: jdbc:mysql://localhost:3306/myblog?useSSL=false
username: root
password: root
driver-class-name: com.mysql.jdbc.Driver

mybatis:
mapper-locations: classpath:sqlmap/*.xml
type-aliases-package: com.bester.platform.platformchain.entity
